
   mbs: main.o
           gcc -o ../bin/mbs ../src/main.c
  
   main.o:../src/main.c
           gcc ../src/main.c
  
   clean:
           rm *.o
                                                                             8         8,8-15        All

	


